server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: com.joker.entity
  config-location: classpath:mybatis-config.xml
logging:
  level:
    com.example.demo.mapper: debug